# Generated by Django 2.1.5 on 2019-10-21 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.IntegerField()),
                ('cat2', models.IntegerField()),
                ('cat3', models.IntegerField()),
                ('cat4', models.IntegerField()),
                ('mouse', models.IntegerField()),
                ('cat_turn', models.BooleanField()),
                ('status', models.CharField(choices=[('CREAT', 'CREATED'), ('ACT', 'ACTIVE'), ('FIN', 'FINISHED')], default='CREAT', max_length=10)),
                ('cat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_user', to=settings.AUTH_USER_MODEL)),
                ('mouse_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouse_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField()),
                ('target', models.IntegerField()),
                ('date', models.DateField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamodel.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
