# Generated by Django 2.1.5 on 2019-11-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='CREATED', max_length=10),
        ),
    ]
