# Generated by Django 2.1.5 on 2019-11-04 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_auto_20191104_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='cat1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat2',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat3',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat4',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat_turn',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse',
            field=models.IntegerField(default=59),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='datamodel.GameStatus'),
        ),
    ]
