# Generated by Django 2.1.5 on 2019-11-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0003_auto_20191104_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatus',
            name='st',
            field=models.CharField(choices=[('C', 'CREATED'), ('A', 'ACTIVE'), ('F', 'FINISHED')], default='C', max_length=15),
        ),
    ]
