# Generated by Django 2.1.5 on 2019-11-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_gamestatus_st'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestatus',
            name='st',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('C', 'CREATED'), ('A', 'ACTIVE'), ('F', 'FINISHED')], default='C', max_length=1),
        ),
    ]
