# Generated by Django 2.1.5 on 2019-11-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0005_auto_20191111_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('Created', 'CREATED'), ('Active', 'ACTIVE'), ('Finished', 'FINISHED')], default='Created', max_length=15),
        ),
    ]
