# Generated by Django 2.1.5 on 2019-11-11 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0006_auto_20191111_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mouse_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouse_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
