# Generated by Django 2.1.5 on 2019-11-11 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0007_auto_20191111_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cat1',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat2',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat3',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat4',
            field=models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse',
            field=models.IntegerField(default=59, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)]),
        ),
    ]
