# Generated by Django 2.1.5 on 2019-11-11 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0010_auto_20191111_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='games_as_cat',
        ),
        migrations.RemoveField(
            model_name='game',
            name='games_as_mouse',
        ),
        migrations.AlterField(
            model_name='game',
            name='cat_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_cat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_mouse', to=settings.AUTH_USER_MODEL),
        ),
    ]
