# Generated by Django 2.1.5 on 2019-11-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0011_auto_20191111_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
