# Generated by Django 2.1.5 on 2019-11-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0014_auto_20191111_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
